### PR TITLE
fix: duplicate comments

### LINKED ISSUE #4291: Comment section sometimes shows the same comments from previous loads
### Steps to reproduce

1. After opening the app, load a page of any video that has a lot of comments
2. Open the comment section
3. Scroll the comment section a few times causing comments to load
4. Issue: comment section sometimes shows the same comments from previous loads

### Expected behavior

Comments that were already shown should be excluded from the next loads of comments

### Actual behavior

Comment section sometimes shows the same comments from previous loads

### LibreTube version

0.16.1

### Android version

13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by salahmak**
Fix #4291

Sometimes, the Piped API's response contains comments that were already given in previous pages, so I have added a filter to remove them.

This might not be the best way to do it, but this is my first time working with Kotlin/Android because I found this bug annoying and wanted to do whatever it takes to fix it, so if there is a better way, please do it.

:)

### CODE REVIEW

**Comment by FireMasterK** [comment]
Can you give an example video where this happens?

**Comment by salahmak** [comment]
@FireMasterK I don't currently have a video of it happening, but it usually happens when doing these steps:

1. Open comments section
2. Scroll down (load 1 or 2 more pages)
3. Open a comment's replies
4. Close the replies
5. Scroll down more comments (load more comments pages)
6. Now you should start noticing it happen

I have confirmed this by checking for duplicates in the `commentPage.comments` List (I didn't include the code in the commit as it was for my debugging) and it confirmed it for me after doing the above steps

**Comment by salahmak** [comment]
What I think is causing the problem is the process of loading the replies of a comment and then going back, perhaps the wrong parameters are being set or overridden. I couldn't get my head around how that transition is happening (as I'm a beginner in Kotlin)

File: app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt [hunk 1]
```diff
@@ -56,9 +56,16 @@ class CommentsViewModel : ViewModel() {
                 Log.e(TAG(), e.toString())
                 return@launch
             }
+
             val updatedPage = commentsPage.value?.apply {
-                comments += response.comments.filterNonEmptyComments()
+                val combinedComments = this.comments + response.comments.filterNonEmptyComments()
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt:61]:
```kotlin
comments += response.comments.filterNonEmptyComments().filter { comment -> comments.none { it.commentId == comment.commented }
```

Comment (Bnyro) [reply app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt:61]: That's more performant and doesn't impac or modify the already visible comments.

Comment (salahmak) [reply app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt:61]: I'll try it and see

Comment (salahmak) [reply app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt]: It works as intended, and I have pushed the commit that uses this. Thanks

**Comment by Bnyro** [comment]
Thank you!

**Comment by salahmak** [comment]
You're welcome @Bnyro, although I still think that this is just a workaround to make it not happen, I'm kinda sure that the cause of the bug is something else related to moving from the comments view to a replies view and then going back.

Opening replies is buggy as well, as sometimes it opens the wrong comment (I'll open a different issue for this).

**Comment by Bnyro** [comment]
Yes, I agree, but it's better to have a temporary workaround/fix instead of keeping the issue present :)
