### PR TITLE
Fix playlist thumbnail change when remove first video

### LINKED ISSUE #2317: Playlist thumbnail not getting updated (using without account)
### Steps to reproduce

Using without account
1. Create a playlist
2. Add some videos to that playlist
3. Open that playlist. The thumbnail of the first video will be the thumbnail of the playlist.
4. Remove that video (first video) from the playlist.
5. The thumbnail of the playlist remains unchanged.

### Expected behavior

The thumbnail of the playlist should change.

### Actual behavior

The playlist thumbnail remains unchanged to the first video which was removed.

### LibreTube version

0.9.0

### Android version

Android 12

### Other details

It is confusing as the playlist thumbnail is of that video which is not in the playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Kruna1Pate1**
Only for local playlists. Not sure if there is any API endpoint to change the thumbnail.

Closes #2317

### CODE REVIEW

File: app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt [hunk 1]
```diff
@@ -175,7 +175,13 @@ object PlaylistsHelper {
             awaitQuery {
                 DatabaseHolder.Database.localPlaylistsDao().removePlaylistVideo(transaction.videos[index])
             }
-            if (transaction.videos.size > 1) return
+            if (transaction.videos.size > 1) {
+                if (index == 0) {
+                    transaction.videos[1].thumbnailUrl?.let { transaction.playlist.thumbnailUrl = it }
+                    DatabaseHolder.Database.localPlaylistsDao().updatePlaylist(transaction.playlist)
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt:181]: That seems to be running on the main thread, wouldn't that crash?

File: app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt [hunk 2]
```diff
@@ -165,20 +168,35 @@ class PlaylistFragment : BaseFragment() {
...
+                        override fun onItemRangeRemoved(positionStart: Int, itemCount: Int) {
+                            if (positionStart == 0) {
+                                ImageHelper.loadImage(
+                                    playlistFeed.firstOrNull()?.thumbnail ?: "",
+                                    binding.thumbnail
+                                )
+                            }
+
+                            val info = binding.playlistInfo.text.split(TextUtils.SEPARATOR)
+                            val countInfo = getString(
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt:188]: I'd prefer that to be used directly instead of assigning it to a var that's only used once.

File: app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt (hunk 1 above)
Comment (Kruna1Pate1) [reply app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt:181]: Yeh, should be awaitQuery.
