### PR TITLE
fix: search is showing inappropriate results

### LINKED ISSUE #5775: Searching in the YT music categories gives strange results
### Describe your suggested feature

Search doesn't work. When searching for someone in channel, playlist, yt music songs and yt music albums, it shows some strange results and I can't get what I want to search for. There is no problem with version 0.21.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Closes #5775

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]

File: app/src/main/java/com/github/libretube/ui/models/SearchResultViewModel.kt [hunk 1]
```diff
@@ -14,13 +14,16 @@ import com.github.libretube.util.TextUtils
...
+import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
 
 class SearchResultViewModel(savedStateHandle: SavedStateHandle) : ViewModel() {
     private val args = SearchResultFragmentArgs.fromSavedStateHandle(savedStateHandle)
 
     // parse search URLs from YouTube entered in the search bar
-    private val videoId = TextUtils.getVideoIdFromUri(args.query.toUri()) ?: args.query
-    private val searchQuery = "${ShareDialog.YOUTUBE_FRONTEND_URL}/watch?v=$videoId"
+    private val searchQuery = args.query.toHttpUrlOrNull()?.let {
+        val videoId = TextUtils.getVideoIdFromUri(args.query.toUri())
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/models/SearchResultViewModel.kt:24]: If the `videoId` is null, the search will use a bad query too

File: app/src/main/java/com/github/libretube/ui/models/SearchResultViewModel.kt [hunk 2]
```diff
@@ -14,13 +14,16 @@ import com.github.libretube.util.TextUtils
...
+        "${ShareDialog.YOUTUBE_FRONTEND_URL}/watch?v=$videoId"
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/models/SearchResultViewModel.kt:25]: If the `videoId` is null, the search will use a bad query too

**Review by Bnyro — CHANGES_REQUESTED** [review]

**Review by Bnyro — APPROVED** [review]
