### PR TITLE
Fixed #2670 : Timestamp click behaviour in the description.

### LINKED ISSUE #2670: Strange Behavior When Clicking on Timestamps
### Steps to reproduce

1. Open a video that has timestamps for different parts. (like [this](https://piped.video/watch?v=l6fVZ0GRbhQ)) 
2.  Click on a timestamp from description 

### Expected behavior

Smooth transition when attempting to play the video from a timestamp

### Actual behavior

https://user-images.githubusercontent.com/50032603/212070703-42c8037e-5a33-4a33-90cf-191fb517f7e8.mp4

### LibreTube version

0.10. 0

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #2723: Player disappears when entered in app from media notification
### Steps to reproduce

1. Play any video
2. Back to home or switch app
3. Tap on player notification 

### Expected behavior

App should open in either player screen or with mini player 

### Actual behavior

Player screen completely disappears 

### LibreTube version

Latest debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/88180887/212749007-9802fe17-837c-4b5f-9f8c-b9ba89d0497c.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by faisalcodes**
- Now clicking on a timestamp in the description plays the video at the specific time.
- Youtube video links are open within the player instead of working like a normal link.

closes #2670 
closes #2723

### CODE REVIEW

**Comment by Bnyro** [comment]
Could you please run `ktlint --android -F` in the root directory of the project and push the changes to your branch? Thanks!

**Comment by faisalcodes** [comment]
@Bnyro I have updated the branch.

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt [hunk 1]
```diff
@@ -1040,6 +1036,119 @@ class PlayerFragment : BaseFragment(), OnlinePlayerOptions {
...
+                                    // get the time in seconds
+                                    val timeInSeconds = getTimeInMillis(time)
+                                    if (timeInSeconds != -1L) {
+                                        // seek to the time
+                                        exoPlayer.seekTo(timeInSeconds)
+                                    }
+                                }
+                                // youtube link without time
+                                // open new player
+                                playNextVideo(videoId)
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1070]: That apparently is still being called even though the player previously seeked to another position in line 1065, so the video will be reloaded although we already figured out it's only a timestamp which is not what we want to achieve.

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt [hunk 2]
```diff
@@ -1040,6 +1036,119 @@ class PlayerFragment : BaseFragment(), OnlinePlayerOptions {
...
+        if (description.contains("<") && description.contains(">")) {
+            descTextView.movementMethod = LinkMovementMethod.getInstance()
+            descTextView.text = HtmlParser.createSpannedText(
+                description,
+                LinkHandler { link ->
+                    // check if the link is a youtube link
+                    if (link.contains("youtube.com") || link.contains("youtu.be")) {
+                        // check if the link is a video link
+                        val videoId = getVideoIdIfVideoLink(link)
+                        if (!videoId.isNullOrEmpty()) {
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1054]: Instead of using lots of if conditions here, we should create a separate function which for example directly opens a new link and returns when the `videoId` is null or empty. That could also be partly applied for the following if conditions, just to keep the code easier to understand.

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt [hunk 3]
```diff
@@ -1040,6 +1036,119 @@ class PlayerFragment : BaseFragment(), OnlinePlayerOptions {
...
+                }
+            )
+        } else {
+            // Links can be present as plain text
+            descTextView.autoLinkMask = Linkify.WEB_URLS
+            descTextView.text = description
+        }
+    }
+
+    private fun getVideoIdIfVideoLink(link: String): String? {
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1097]: That's not needed, instead we should first parse the URL with `Uri#parse` and then use `uri.getQueryParameter` instead of manually splitting strings

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt [hunk 4]
```diff
@@ -1040,6 +1036,119 @@ class PlayerFragment : BaseFragment(), OnlinePlayerOptions {
...
+        if (link.contains("youtube.com")) {
+            // check if the link is a channel link
+            val videoId = link.substringAfter("v=").substringBefore("&")
+            if (videoId.isNotEmpty() && videoId != link) {
+                return videoId
+            }
+        } else if (link.contains("youtu.be")) {
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1104]: Instead of splitting strings, we should use the path from the Uri generated above

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt [hunk 5]
```diff
@@ -1040,6 +1036,119 @@ class PlayerFragment : BaseFragment(), OnlinePlayerOptions {
...
+        if (time.contains("m")) {
+            val longOrNull = time.substringBefore("m").substringAfter("s").toLongOrNull()
+            if (longOrNull != null) {
+                timeInSeconds += longOrNull * 60
+                found = true
+            }
+        }
+        // check if the time is in hours
+        if (time.contains("h")) {
+            val longOrNull = time.substringBefore("h").substringAfter("m").toLongOrNull()
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1134]: Instead, please use something like ```kotlin
time.substringBefore("h").substringAfter("m").toLongOrNull()?.let {
    timeInSeconds += longOrNull * 60 * 60
    found = true
}
```
here

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt [hunk 6]
```diff
@@ -1040,6 +1036,119 @@ class PlayerFragment : BaseFragment(), OnlinePlayerOptions {
...
+            if (longOrNull != null) {
+                timeInSeconds += longOrNull * 60 * 60
+                found = true
+            }
+        }
+
+        if (!found) {
+            val longOrNull = time.toLongOrNull()
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1142]: Same as the comment a few lines above

File: app/src/main/java/com/github/libretube/util/LinkHandler.kt [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+class LinkHandler(private val clickCallback: ((String) -> Unit)?) : HtmlParser.TagHandler {
+    private var linkTagStartIndex = -1
+    private var link: String? = null
+    override fun handleTag(
+        opening: Boolean,
+        tag: String?,
+        output: Editable?,
+        attributes: Attributes?
+    ): Boolean {
+        if (output != null) {
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/util/LinkHandler.kt:20]: These if conditions should be replaced with with some return statements instead.

File: app/src/main/java/com/github/libretube/util/HtmlParser.kt [hunk 8]
```diff
@@ -0,0 +1,134 @@
...
+import android.text.Html
+import android.text.Spanned
+import androidx.core.text.HtmlCompat
+import org.xml.sax.Attributes
+import org.xml.sax.ContentHandler
+import org.xml.sax.Locator
+import org.xml.sax.SAXException
+import org.xml.sax.XMLReader
+
+class HtmlParser private constructor(private val handler: TagHandler) :
```
Comment (Bnyro) [inline app/src/main/java/com/github/libretube/util/HtmlParser.kt:13]: Why using a private constructor here?

**Comment by Bnyro** [comment]
I'm not really a fan of that `HTMLParser` as it's quite large in code size although it doesn't really do much, maybe we can find some better way to do that or remove some unused/unneeded parts of it.

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt (hunk 2 above)
Comment (faisalcodes) [reply app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1054]: I did this because the link could also be a channel or playlist link. In future we can open channel or playlist within the app instead of opening an external intent.

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt (hunk 1 above)
Comment (faisalcodes) [reply app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1070]: Sorry, here I forgot an else condition. I must fix this by merging both  `playNextVideo(videoId)`.

File: app/src/main/java/com/github/libretube/util/HtmlParser.kt (hunk 8 above)
Comment (faisalcodes) [reply app/src/main/java/com/github/libretube/util/HtmlParser.kt:13]: To get what we need, we do need to override the link handling. This is the only way I find to be useful to handle timestamps because we could not find any callback from the default implementations.

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt (hunk 1 above)
Comment (faisalcodes) [reply app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1070]: Fortunately video was not reloading because in `playNextVideo` it checks for difference.

File: app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt (hunk 5 above)
Comment (faisalcodes) [reply app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt:1134]: Pardons but i thought this would be more readable.

File: app/src/main/java/com/github/libretube/util/HtmlParser.kt (hunk 8 above)
Comment (faisalcodes) [reply app/src/main/java/com/github/libretube/util/HtmlParser.kt:13]: I am making it short.

**Comment by Bnyro** [comment]
Works awesome, thank you!
