### PR TITLE
Replace the `PlayerNotificationManager` with a custom implementation

### LINKED ISSUE #3059: App not opening from notification.
### Steps to reproduce

1. Play any video
2. Return to home screen or any other app
3. Slide down notification panel
4. Click on LibreTube player notification 
5. Tap the player notification 
Screenshot_20230213-222932-347

### Expected behavior

App/video player should open 

### Actual behavior

The notification planel just slides up and the app remains in the background. If the video is playing, it remains playing in the background but the app doesn't open.

### LibreTube version

0.12.0

### Android version

Android 12

### Other details

The player notification and it's buttons like play/pause and seek bar itself are working. It's just that the app is not opening on tapping.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #3811: Pressing now playing notification doesnt open app after media3 migration!
### Steps to reproduce

play any video and throw the app to background by tapping home screen or the audio button
pull quick switch and tap now playing notification

### Expected behavior

the app should open

### Actual behavior

but the notification panel gets closed and app is not launched

### LibreTube version

Latest Alpha

### Android version

A13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
* The main goal of these changes is to allow ourselves to have more control over the notification itself since the `PlayerNotificationManager` API is very limited in its possibilities.
* Should be tested intensively on different Android versions once again since the notification behavior differs on recent Android versions
* Kill the background player when swiping its notification away on SDK 27 and below
* Already tested on SDK 33 and SDK 25 by me

closes #3811
closes #3059

### CODE REVIEW

File: app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt [hunk 1]
```diff
@@ -281,55 +256,89 @@ class NowPlayingNotification(
...
+        notificationBuilder = NotificationCompat.Builder(context, BACKGROUND_CHANNEL_ID)
+            .setSmallIcon(R.drawable.ic_launcher_lockscreen)
+            .setContentIntent(createCurrentContentIntent())
+            .setStyle(
+                MediaStyleNotificationHelper.MediaStyle(mediaSession)
+                    .setShowActionsInCompactView(1)
+            )
+    }
+
+    @SuppressLint("MissingPermission")
```
Comment (Isira-Seneviratne) [inline app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt:292]: This can be removed with the above change.

**Comment by Bnyro** [comment]
@xIUPITERx @rozari0 @akano12, if some of you have some time left, could you please test the apk from this PR's actions and search for any regressions concerning the notification while playing a video (in background or in normal video mode)?
Thanks in advance!

**Comment by FireMasterK** [comment]
Open it in a browser, the app doesn't support it I think.

**Comment by akano12** [comment]
@xIUPITERx

Login to your github account from any web browser (desktop/mobile).
In the top right corner (after you click the link above) you'll see the word "artifacts".
Click it then download the zipped file and install the app of your device architecture
